### ISSUE TITLE
Mobile responsivness

### ISSUE THREAD

**Issue by sorvis** [CloudCannon/justice-eleventy-template#3]
It appears that its not quite so responsive for mobile viewers. Perhaps the main menu should become a hamburger menu?

![image](https://user-images.githubusercontent.com/1037467/190853847-0d6b405d-da73-4d60-86fd-6ddcc824d172.png)

**Comment by kate-ferguson** [comment]
Hey @sorvis, thanks for letting us know about this issue. I have updated our scss, so this shouldn't be an issue anymore. Hope this helps!
